name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Lint import
        run: |
          python - <<'PY'
          import importlib
          import sys
          for m in [
            'fastapi','uvicorn','sqlmodel','pydantic','httpx'
          ]:
            importlib.import_module(m)
          print('Deps OK')
          PY





